var _STRINGS = {
	"Ad":{
		"Mobile":{
			"Preroll":{
				"ReadyIn":"The game is ready in ",
				"Loading":"Your game is loading...",
				"Close":"Close",
			},
			"Header":{
				"ReadyIn":"The game is ready in ",
				"Loading":"Your game is loading...",
				"Close":"Close",
			},
			"End":{
				"ReadyIn":"Advertisement ends in ",
				"Loading":"Please wait ...",
				"Close":"Close",
			},								
		},
	},
	
	"Splash":{
		"Loading":"Loading ...",	
		//"LogoLine1":"Some text here",
		//"LogoLine2":"powered by MarketJS",
		"LogoLine3":"none", 
        "TapToStart":"TAP TO START", 
	},

	"Menu":{
		"Play":"Play",
		"MoreGames":"More Games"
	},

	"Settings":{
		"Header":"SETTINGS",
		"ButtonOk":"OK"
	},

	"Pause":{
		"Header":"PAUSED",
		"ButtonTutorial":"?"
	},

	"Game":{
		"Wrong1":"Whoops! It's wrong.",
		"Wrong2":"Whoops!",
		"ButtonNext":"Next",
		"ButtonPrev":"Prev",
		"Theme1":{"ant":"Ant",
				"bird":"Bird",
				"butterfly":"Butterfly",
				"cow":"Cow",
				"crab":"Crab",
				"dino":"Dino",
				"donkey":"Donkey",
				"duck":"Duck",
				"elephant":"Elephant",
				"fish":"Fish",
				"goat":"Goat",
				"jellyfish":"Jellyfish",
				"octopus":"Octopus",
				"owl":"Owl",
				"sheep":"Sheep",
				"spider":"Spider",
				"cow_sheep":"Cow and Sheep",
				"duck_owl":"Duck and Owl",
				"donkey_sheep":"Donkey and Sheep",
				"crab_octopus":"Octopus and Crab",
				"ant_spider":"Spider and Ant",
				"elephant_cow":"Elephant and Cow",
				"goat_sheep":"Goat and Sheep",
				"jellyfish_octopus":"Jellyfish and Octopus",
				"owl_butterfly":"Owl and Butterfly",
				"sheep_dino":"Sheep and Dino",
				"dino_duck":"Dino and Duck",
				"donkey_elephant":"Donkey and Elephant",
				"bird_butterfly":"Bird and Butterfly",
				"cow_dino":"Cow and Dino"},
		"Theme2":{"ball":"Ball",
				"beachball":"Beach Ball",
				"bell":"Bells",
				"boat":"Boat",
				"book":"Book",
				"cap":"Cap",
				"car":"Car",
				"kettle":"Kettle",
				"door":"Door",
				"fences":"Fence",
				"glasses":"Glasses",
				"key":"Key",
				"milk":"Milk",
				"present":"Present",
				"ribbon":"Ribbon",
				"shelltrumpet":"Shell Trumpet",
				"slide":"Slide",
				"tricycle":"Tricycle",
				"umbrella":"Umbrella",
				"wateringcan":"Watering Can",
				"ball_beachball":"Ball and Beach Ball",
				"kettle_milk":"Kettle and Milk",
				"glasses_ribbon":"Ribbon and Glasses",
				"book_gift":"Gift and Book",
				"car_slide":"Slide and Car",
				"door_umbrella":"Door and Umbrella",
				"slide_tricycle":"Slide and Tricycle",
				"book_glasses":"Book and Glasses",
				"bell_ribbon":"Ribbon and Bells",
				"cap_glasses":"Glasses and Cap"},
		"Theme3":{"apple":"Apple",
				"banana":"Banana",
				"bush":"Bush",
				"cloud":"Cloud",
				"coconut":"Coconut",
				"coconuttree":"Coconut Tree",
				"coral":"Coral",
				"flower":"Flowers",
				"moon":"Moon",
				"mushroom":"Mushroom",
				"pearl":"Pearl",
				"rainbow":"Rainbow",
				"rambutan":"Rambutan",
				"river":"River",
				"rock":"Rock",
				"seashell":"Seashell",
				"seaweed":"Seaweed",
				"shrub":"Shrub",
				"star":"Star",
				"sun":"Sun",
				"tree":"Tree",
				"apple_coconut":"Apple and Coconut",
				"sun_cloud":"Cloud and Sun",
				"coconuttree_bush":"Coconut Tree and Bush",
				"star_moon":"Moon and Star",
				"pearl_coral":"Pearl and Coral",
				"rock_mushroom":"Rock and Mushroom",
				"seashell_seaweed":"Seaweed and Seashell",
				"rambutan_banana":"Rambutan and Banana",
				"rainbow_flower":"Rainbow and Flowers"},
		"Theme4":{"aunty":"\"Aunty Wendy the Panda''",
				"bee":"\"Lebah the Bee''",
				"bingo":"\"Bingo the Cat''",
				"dani":"\"Dani the Fish''",
				"didi":"\"Didi the Chicken''",
				"happy-bear":"\"Happy Bear''",
				"jay":"\"Jay the Fish''",
				"jojo":"\"Jojo the Chicken''",
				"kiki":"\"Kiki the Parrot''",
				"kwek":"\"Kwek the Duck''",
				"mimi":"\"Mimi the Squirrel''",
				"moon":"\"Mon the Monkey''",
				"nana":"\"Nana the Chicken''",
				"nina":"\"Nina the Shark''",
				"pak-atan":"\"Pak Atan the Orang Utan''",
				"pak-beruang":"\"Pak Beruang the Bear''",
				"pipi":"\"Pipi the Penguin''",
				"sophie":"\"Sofi the Rabbit''",
				"sumiika":"\"Sumi & Ika the Turtles''",
				"tally":"\"Tally the Giraffe''",
				"tatak":"\"Tatak the Frog''",
				"tiya":"\"Tiya the Hamster''",
				"wawa":"\"Wawa the Bee''",
				"nana_didi":"Nana and Didi",
				"kiki_tatak":"Kiki and Tatak",
				"bingo_sophie":"Bingo and Sofi",
				"nina_dani":"Nina and Dani",
				"didi_jojo":"Didi and Jojo",
				"happy_bear_moon":"Happy Bear and Mon",
				"tiya_pipi":"Tiya and Pipi"},
	},

	"PostGame":{
		"Header":"Theme\nCompleted"
	},

	"ThemeRetry":{
		"Header":"Theme\nCompleted",
		"Message":"Start from the Beginning?"
	},

	"Tutorial":{
		"Header":"Tutorial"
	}
};